# syntax=docker/dockerfile:1

# Pin specific Bun version for stable builds and better caching
FROM oven/bun:1.3.3-alpine AS base

# Build arguments
# Sentry args removed - source maps uploaded separately in CI

# Disabling Telemetry
ENV NEXT_TELEMETRY_DISABLED=1

# Pin Alpine package versions for cache stability
# Note: These versions are compatible with Alpine 3.19 (base image's Alpine version)
RUN apk add --no-cache \
    libc6-compat~=1.2 \
    curl~=8.9 \
    wget~=1.24 \
    bash~=5.2 \
    openssl~=3.1

FROM base AS deps
WORKDIR /app

# Copy package files and prisma schema
COPY package.json bun.lock ./
COPY prisma ./prisma

# Install dependencies with cache mount (unique id per project to avoid conflicts)
RUN --mount=type=cache,id=bun-tiktoks,target=/root/.bun/install/cache \
    bun install --frozen-lockfile

FROM base AS builder
WORKDIR /app

# Set NODE_ENV for production build (ensures correct distDir and optimizations)
ENV NODE_ENV=production

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate Prisma client (if not already generated by postinstall)
RUN bunx prisma generate

# Build with Next.js cache mount (unique id per project to avoid conflicts)
# Note: Sentry source maps are disabled during Docker build
# They will be uploaded separately in CI to avoid rebuilding
ENV SENTRY_SUPPRESS_UPLOAD=true
RUN --mount=type=cache,id=nextjs-tiktoks,target=/app/.next/cache \
    bun run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
RUN mkdir .next && chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
# Copy complete node_modules to include all Prisma WASM files
COPY --from=deps --chown=nextjs:nodejs /app/node_modules ./node_modules

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["sh", "-c", "bunx prisma migrate deploy && node server.js"]
